FROM itdoginfo/openwrt-sdk-apk:09102025

ARG PADKAP_VERSION
ENV PADKAP_VERSION=${PADKAP_VERSION}

COPY ./padkap /builder/package/feeds/utilities/padkap
COPY ./luci-app-padkap /builder/package/feeds/luci/luci-app-padkap

RUN make defconfig && \
    make package/padkap/compile -j1 V=s && \
    make package/luci-app-padkap/compile -j1 V=s