FROM itdoginfo/openwrt-sdk-ipk:24.10.3

ARG PADKAP_VERSION

COPY ./padkap /builder/package/feeds/utilities/padkap
COPY ./luci-app-padkap /builder/package/feeds/luci/luci-app-padkap

RUN export PADKAP_VERSION="v${PADKAP_VERSION}" && \
    make defconfig && \
    make package/padkap/compile V=s -j4 && \
    make package/luci-app-padkap/compile V=s -j4